export const advices = [
  'Do not waste time reading trash.',
  'Do not lay on the grass.',
  'Do not lose sight of the fact.',
  'Do not do anything heat of the moment.',
  'Help any needy person.',
  'Take your medicine regularly.',
  "Don't lie to me.",
  'Try hard and you will succeed.',
  'Get rid of your bad habit.',
  "Don't be rude to anybody.",
  "Don't sneer at me.",
  'Think carefully over his advice.',
  'Be true to your word.',
  "Don't ignore your son's faults.",
  "Don't run too fast.",
  "Don't cry down your enemy.",
  'Prepare your lessons carefully.',
  'Get up at five in the morning.',
  "Don't go aside from the path of virtue.",
  'Hold in your temper.',
  'Stick to your promise.',
  'Hold up your spirit for a few days more.',
  "Don't look down upon the poor.",
  'Put back the book in its proper place.',
  "Don't stand against the force of time.",
  "Don't turn back a beggar from your door.",
  "Don't go out in the sun.",
  'You better consult a doctor.',
  "Don't worry about my family.",
  "You mustn't play with fire.",
  'No one should disturb him.',
  'Get some fresh air outside.',
  'You must look for the painting.',
  "Don't look at me that way.",
  'You should trust your wife in this matter.',
  'You should follow my advice closely in every detail.',
  "Don't make any sound.",
  'Go there by bus.',
  'Follow in the steps of one who is wise.',
  'Look at your certificates later.',
  'Try hard so that you may win.',
  "Don't spend more than you cannot help.",
  'Do not stop on the way but go home direct.',
  'Attend to your work.',
  'Do not jump to a conclusion.',
  'Try to come between three and five.',
  'Stick to the truth at all costs.',
  'Do your duty by all means.',
  'Do your work in earnest.',
  'Take my advice in good part.',
];
